version: '3'
services:
  influxdb:
    image: influxdb:latest
    ports:
      - "8086:8086"
    environment: 
       # Use these same configurations parameters in your telegraf configuration, mytelegraf.conf.
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=chuvicka
      - DOCKER_INFLUXDB_INIT_PASSWORD=passwordChuvicka
      - DOCKER_INFLUXDB_INIT_ORG=myorg
      - DOCKER_INFLUXDB_INIT_BUCKET=chuvicka
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=$INFLUXDB_TOKEN

  postgres:
    image: 'postgres:15'
    ports:
      - 5432:5432

    environment:
      POSTGRES_USER: chuvicka
      POSTGRES_PASSWORD: passwordChuvicka
      POSTGRES_DB: chuvicka
